name: Build

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: radcortez/maven-dependencies-action@main
        name: build dependencies

      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml
