name: Build

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

#      - uses: radcortez/maven-dependencies-action@main
#        name: build dependencies
#        with:
#          repository: |
#            eclipse/microprofile-config
#            smallrye/smallrye-config
#
#      - name: copy dependencies
#        run: cp -r /home/runner/work/_temp/_github_home/.m2 $HOME

      - uses: actions/checkout@v2
        name: checkout

      - name: build with maven
        run: mvn -B verify --file pom.xml
